chore: commit changes (1/2)

diff --git a/.local/bin/nvim b/.local/bin/nvim
--- a/.local/bin/nvim
+++ b/.local/bin/nvim
@@ -1,105 +1,105 @@
 #!/bin/sh
 
-[ "$(whoami)" = 'root' ] && {
-  echo >&2 "Error: Do not run as root"
-  exit 1
+# Generate a read-only list of known hosts, to clone plugins from
+# Parameters: list of FQDNs
+git_ssh_prepare() {
+	# Ensure parent direcotory exists
+	: "${KNOWN_HOSTS:=$HOME/.ssh/bwrap_hosts}"
+	mkdir -p "${KNOWN_HOSTS%/*}"
+
+	# This loop will run only as needed
+	for website in "$@"; do
+		# Skip if website is known
+		if ! grep -q "$website" "$KNOWN_HOSTS"; then
+			# Get the key
+			if ! ssh-keyscan "$website" >>"$KNOWN_HOSTS"; then
+				echo >&2 "Error: Cannot touch $KNOWN_HOSTS"
+				exit 1
+			fi
+		fi
+	done
 }
 
+# Root should not run a heavely modded neovim
+[ "$(whoami)" = 'root' ] && {
+	echo >&2 "Error: Do not run as root"
+	exit 1
+}
+
+# Respect user defined XDGs
 : "${XDG_CONFIG_HOME:=$HOME/.config}"
 : "${XDG_DATA_HOME:=$HOME/.local/share}"
 : "${XDG_STATE_HOME:=$HOME/.local/state}"
 : "${XDG_CACHE_HOME:=$HOME/.cache}"
 
+# Fail if runtime dir is unset (rather than setting)
 [ -r "$XDG_RUNTIME_DIR" ] || {
-  echo >&2 "Error: Can't read directory: XDG_RUNTIME_DIR"
-  exit 1
+	echo >&2 "Error: Can't read directory: XDG_RUNTIME_DIR"
+	exit 1
 }
 
+# Prevent running from very personal directories
 PWD=$(pwd)
 case "$PWD" in
 "$HOME")
-  echo >&2 "Error: Do not run from HOME"
-  exit 1
-  ;;
+	echo >&2 "Error: Do not run from HOME"
+	exit 1
+	;;
 "$HOME"/*)
-  case "${PWD#"$HOME"/}" in
-  */*)
-    ;;
-  *)
-    echo >&2 "Error: Do not run from direct child of HOME"
-    exit 1
-    ;;
-  esac
-  ;;
+	case "${PWD#"$HOME"/}" in
+	*/*)
+		;;
+	*)
+		echo >&2 "Error: Do not run from direct child of HOME"
+		exit 1
+		;;
+	esac
+	;;
 esac
 
-# Ensure KNOWN_HOSTS exists
-: "${KNOWN_HOSTS:=$HOME/.ssh/bwrap_hosts}"
-mkdir -p "${KNOWN_HOSTS%/*}" \
+# Add sites to clone plugins from
+git_ssh_prepare github.com gitlab.com codeberg.org
 
-# Skip if already has github.com
-if ! grep -q github.com "$KNOWN_HOSTS"; then
-  if ! ssh-keyscan github.com >> "$KNOWN_HOSTS"; then
-    echo >&2 "Error: Cannot touch $KNOWN_HOSTS"
-    exit 1
-  fi
-fi
-
+# Configure SSH line
 GIT_SSH_COMMAND="ssh -F /dev/null -o UserKnownHostsFile=$KNOWN_HOSTS"
 
 # Ensure source paths exist
-mkdir -p \
-  "$HOME"/git \
-  "$XDG_CONFIG_HOME" \
-  "$HOME"/.local/bin \
-  "$XDG_DATA_HOME"/nvim \
-  "$XDG_DATA_HOME"/zsh \
-  "$XDG_STATE_HOME"/nvim \
-  "$XDG_CACHE_HOME"/nvim \
-  "$XDG_RUNTIME_DIR"/nvim
+mkdir -p "$XDG_RUNTIME_DIR"/nvim
 
 # Execute the sandbox
 exec bwrap \
-  --ro-bind /usr /usr \
-  --ro-bind /lib /lib \
-  --ro-bind /lib64 /lib64 \
-  --ro-bind /bin /bin \
-  --ro-bind /etc /etc \
-  --dev /dev \
-  --proc /proc \
-  --tmpfs /tmp \
-  --ro-bind /run/systemd/resolve /run/systemd/resolve \
-  --ro-bind /tmp/.X11-unix /tmp/.X11-unix \
-  --ro-bind "$XAUTHORITY" "$XAUTHORITY" \
-  --ro-bind "$XDG_RUNTIME_DIR/$WAYLAND_DISPLAY" "$XDG_RUNTIME_DIR/$WAYLAND_DISPLAY" \
-  --ro-bind "$XDG_RUNTIME_DIR/pulse" "$XDG_RUNTIME_DIR/pulse" \
-  --setenv DISPLAY "$DISPLAY" \
-  --setenv WAYLAND_DISPLAY "$WAYLAND_DISPLAY" \
-  --setenv XAUTHORITY "$XAUTHORITY" \
-  --setenv XDG_RUNTIME_DIR "$XDG_RUNTIME_DIR" \
-  --setenv PULSE_SERVER "unix:/$XDG_RUNTIME_DIR/pulse/native" \
-  --dir  "$HOME"/git \
-  --bind "$HOME"/git "$HOME"/git \
-  --dir  "$XDG_CONFIG_HOME" \
-  --bind "$XDG_CONFIG_HOME" "$XDG_CONFIG_HOME" \
-  --dir  "$HOME"/.local \
-  --dir  "$HOME"/.local/bin \
-  --bind "$HOME"/.local/bin "$HOME"/.local/bin \
-  --dir  "$XDG_DATA_HOME" \
-  --dir  "$XDG_DATA_HOME"/nvim \
-  --bind "$XDG_DATA_HOME"/nvim "$XDG_DATA_HOME"/nvim \
-  --dir  "$XDG_DATA_HOME"/zsh \
-  --bind "$XDG_DATA_HOME"/zsh "$XDG_DATA_HOME"/zsh \
-  --dir  "$XDG_STATE_HOME" \
-  --dir  "$XDG_STATE_HOME"/nvim \
-  --bind "$XDG_STATE_HOME"/nvim "$XDG_STATE_HOME"/nvim \
-  --dir  "$XDG_CACHE_HOME"/nvim \
-  --bind "$XDG_CACHE_HOME"/nvim "$XDG_CACHE_HOME"/nvim \
-  --dir  "$XDG_RUNTIME_DIR"/nvim \
-  --bind "$XDG_RUNTIME_DIR"/nvim "$XDG_RUNTIME_DIR"/nvim \
-  --setenv GIT_SSH_COMMAND "$GIT_SSH_COMMAND" \
-  --bind "$KNOWN_HOSTS" "$KNOWN_HOSTS" \
-  --unshare-all \
-  --share-net \
-  --die-with-parent \
-  /usr/bin/nvim "$@"
+	--ro-bind /usr /usr \
+	--ro-bind /lib /lib \
+	--ro-bind /lib64 /lib64 \
+	--ro-bind /bin /bin \
+	--ro-bind /etc /etc \
+	--dev /dev \
+	--proc /proc \
+	--tmpfs /tmp \
+	--ro-bind /run/systemd/resolve /run/systemd/resolve \
+	--ro-bind /tmp/.X11-unix /tmp/.X11-unix \
+	--ro-bind "$XAUTHORITY" "$XAUTHORITY" \
+	--ro-bind "$XDG_RUNTIME_DIR/$WAYLAND_DISPLAY" "$XDG_RUNTIME_DIR/$WAYLAND_DISPLAY" \
+	--setenv DISPLAY "$DISPLAY" \
+	--setenv WAYLAND_DISPLAY "$WAYLAND_DISPLAY" \
+	--setenv XAUTHORITY "$XAUTHORITY" \
+	--setenv XDG_RUNTIME_DIR "$XDG_RUNTIME_DIR" \
+	--bind "$HOME"/vimwiki "$HOME"/vimwiki \
+	--bind "$HOME"/git "$HOME"/git \
+	--bind "$HOME"/.local/bin "$HOME"/.local/bin \
+	--bind "$XDG_CONFIG_HOME" "$XDG_CONFIG_HOME" \
+	--bind "$XDG_DATA_HOME"/nvim "$XDG_DATA_HOME"/nvim \
+	--bind "$XDG_DATA_HOME"/zsh "$XDG_DATA_HOME"/zsh \
+	--bind "$XDG_STATE_HOME"/nvim "$XDG_STATE_HOME"/nvim \
+	--bind "$XDG_CACHE_HOME"/nvim "$XDG_CACHE_HOME"/nvim \
+	--bind "$XDG_CACHE_HOME"/zsh "$XDG_CACHE_HOME"/zsh \
+	--bind "$XDG_CACHE_HOME"/antidote "$XDG_CACHE_HOME"/antidote \
+	--bind "$XDG_RUNTIME_DIR"/nvim "$XDG_RUNTIME_DIR"/nvim \
+	--bind "$XDG_RUNTIME_DIR"/zsh "$XDG_RUNTIME_DIR"/zsh \
+	--bind "$XDG_RUNTIME_DIR"/dconf "$XDG_RUNTIME_DIR"/dconf \
+	--setenv GIT_SSH_COMMAND "$GIT_SSH_COMMAND" \
+	--bind "$KNOWN_HOSTS" "$KNOWN_HOSTS" \
+	--unshare-all \
+	--share-net \
+	--die-with-parent \
+	/usr/bin/nvim "$@"
