chore: cleanup

diff --git a/.local/bin/nvim b/.local/bin/nvim
--- a/.local/bin/nvim
+++ b/.local/bin/nvim
@@ -1,50 +1,43 @@
 #!/bin/sh
 
 if [ "$(id -u)" -eq 0 ]; then
-  echo >&2 "Do not run as root"
-  exit 1
-fi
-
-if [ -z "$XDG_RUNTIME_DIR" ]; then
-  echo >&2 "XDG_RUNTIME_DIR is unset"
+  echo >&2 "Error: Do not run as root"
   exit 1
 fi
 
 case "$(pwd)" in
-"$HOME"/.config*)    : break ;;
-"$HOME"/.local/bin*) : break ;;
-"$HOME"/diary*)      : break ;;
-"$HOME"/git*)        : break ;;
-*)
-  echo >&2 "Do not run from $(pwd)"
-  exit 1
-  ;;
+"$HOME"|"$HOME"/*/)
+  echo >&2 "Error: Do not run from $(pwd)"
+  exit 1 ;;
 esac
 
+XDG_RUNTIME_DIR="${XDG_RUNTIME_DIR:-/run/user/"$(id -u)"}"
 WAYLAND_SOCKET="$XDG_RUNTIME_DIR/$WAYLAND_DISPLAY"
 
-mkdir -p "$XDG_RUNTIME_DIR/nvim" || exit 1
+mkdir -p "$XDG_RUNTIME_DIR/nvim"
 
-bwrap \
-  --unshare-all \
-  --unshare-net \
+exec bwrap \
   --die-with-parent \
+  --unshare-all \
+  --share-net \
   --ro-bind /usr /usr \
-  --ro-bind /bin /bin \
   --ro-bind /lib /lib \
   --ro-bind /lib64 /lib64 \
   --ro-bind /bin /bin \
   --ro-bind /etc /etc \
-  --ro-bind /run/systemd/resolve /run/systemd/resolve \
-  --dev /dev \
-  --dev-bind /dev/shm /dev/shm \
   --proc /proc \
+  --dev /dev \
   --tmpfs /tmp \
+  --ro-bind /run/systemd/resolve /run/systemd/resolve \
   --ro-bind /tmp/.X11-unix /tmp/.X11-unix \
   --ro-bind "$XAUTHORITY" "$XAUTHORITY" \
   --ro-bind "$WAYLAND_SOCKET" "$WAYLAND_SOCKET" \
-  --ro-bind "$HOME/.config/nvim" "$HOME/.config/nvim" \
+  --bind "$HOME/git" "$HOME/git" \
+  --bind "$HOME/.config" "$HOME/.config" \
+  --bind "$HOME/.config/nvim" "$HOME/.config/nvim" \
+  --bind "$HOME/.local/bin" "$HOME/.local/bin" \
   --bind "$HOME/.local/share/nvim" "$HOME/.local/share/nvim" \
+  --bind "$HOME/.local/share/zsh" "$HOME/.local/share/zsh" \
   --bind "$HOME/.local/state/nvim" "$HOME/.local/state/nvim" \
   --bind "$HOME/.cache/nvim" "$HOME/.cache/nvim" \
   --bind "$XDG_RUNTIME_DIR/nvim" "$XDG_RUNTIME_DIR/nvim" \
@@ -52,6 +45,6 @@ bwrap \
   --chdir "$(pwd)" \
   --setenv DISPLAY "$DISPLAY" \
   --setenv WAYLAND_DISPLAY "$WAYLAND_DISPLAY" \
-  --setenv XAUTHORITY $XAUTHORITY \
+  --setenv XAUTHORITY "$XAUTHORITY" \
   --setenv XDG_RUNTIME_DIR "$XDG_RUNTIME_DIR" \
   /usr/bin/nvim "$@"
