feat!: new statusbar

diff --git a/.local/bin/statusbar/sb-battery b/.local/bin/statusbar/sb-battery
--- a/.local/bin/statusbar/sb-battery
+++ b/.local/bin/statusbar/sb-battery
@@ -1,40 +1,147 @@
-#!/bin/bash
-shopt -s failglob
+#!/bin/sh
+
+# ########
+# Helper
+# ########
+
+die() {
+  echo >&2 "$1"
+  exit 1
+}
+
+command_exists() {
+  command -v "$1" >/dev/null 2>&1 || return 1
+}
+
+super() {
+  if command_exists doas; then
+    doas "$@"
+  elif command_exists sudo; then
+    sudo "$@"
+  else
+    die "Error: Unknown escalation tool"
+  fi
+}
+
+check_env() {
+  # Make zsh behave more like POSIX
+  emulate sh 2>/dev/null
+
+  # Prevent root from running
+  [ "$(id -u)" -eq 0 ] && die "Do not run as root"
+
+  # Ensure environment variables are set
+  [ -z "$TERMINAL" ] || [ -z "$EDITOR" ] && die "TERMINAL or EDITOR is unset"
+
+  # Add a comment here too because I can
+  deps="$TERMINAL $EDITOR acpi tlp"
+  for dep in $deps; do
+    command_exists "$dep" || die "$dep is not installed"
+  done
+}
+
+notify_batteries() {
+  notify-send \
+    --icon=battery-good-symbolic \
+    --expire-time=10000 \
+    --hint=string:x-canonical-private-synchronous:battery \
+    "Battery Report" "$1"
+}
+
+get_progress() {
+  percent=$1
+
+  if [ "$percent" -le 10 ]; then
+    line="[░░░░░░░░░░]"
+  elif [ "$percent" -le 20 ]; then
+    line="[█░░░░░░░░░]"
+  elif [ "$percent" -le 30 ]; then
+    line="[██░░░░░░░░]"
+  elif [ "$percent" -le 40 ]; then
+    line="[███░░░░░░░]"
+  elif [ "$percent" -le 50 ]; then
+    line="[████░░░░░░]"
+  elif [ "$percent" -le 60 ]; then
+    line="[█████░░░░░]"
+  elif [ "$percent" -le 70 ]; then
+    line="[██████░░░░]"
+  elif [ "$percent" -le 80 ]; then
+    line="[███████░░░]"
+  elif [ "$percent" -le 90 ]; then
+    line="[████████░░]"
+  elif [ "$percent" -le 99 ]; then
+    line="[█████████░]"
+  else
+    line="[██████████]"
+  fi
+
+  echo "$line"
+}
 
 get_batteries() {
-  local line
   for battery in /sys/class/power_supply/BAT?*; do
-    local status capacity
-
     status="$(cat "$battery"/status 2>&1)"
     capacity="$(cat "$battery"/capacity 2>&1)"
 
-    local icon
-    if [[ $status == "Charging" ]]; then
-      icon=""
-    else
-      if [[ $capacity -le 10 ]]; then
-        icon="" # 0-10
-      elif [[ $capacity -le 30 ]]; then
-        icon="" # 10-30
-      elif [[ $capacity -le 70 ]]; then
-        icon="" # 30-70
-      elif [[ $capacity -le 90 ]]; then
-        icon="" # 70-90
-      else
-        icon="" # 90-100
-      fi
+    if [ -z "$status" ] || [ -z "$capacity" ]; then
+      die "Error: Something went wrong"
     fi
 
-    if [[ -n $line ]]; then
-      line="$icon ${capacity}% $line"
+    if [ "$status" = "Full" ]; then
+      icon=""
+    elif [ "$status" = "Not charging" ]; then
+      icon=""
+    elif [ "$status" = "Charging" ]; then
+      icon=""
+    elif [ "$capacity" -le 10 ]; then
+      icon="" # 0-10
+    elif [ "$capacity" -le 40 ]; then
+      icon="" # 10-40
+    elif [ "$capacity" -le 60 ]; then
+      icon="" # 40-60
+    elif [ "$capacity" -le 90 ]; then
+      icon="" # 60-90
     else
-      line="$icon ${capacity}%"
+      icon="" # 90-100
+    fi
+
+    # Source theme
+    . ~/.local/bin/statusbar/themes/gruvbox-dark.sh
+
+    # Load up the progress bar
+    progress=$(get_progress "$capacity")
+
+    # Decide how to display everything
+    # NOTE: No trailing spaces when concatenating $line
+    if [ -n "$line" ]; then
+      echo "$theme $icon ${capacity}% $progress $reset $line"
+    else
+      echo "$theme $icon ${capacity}% $progress $reset"
     fi
   done
 
   echo "$line"
 }
 
-get_batteries
+# ########
+# Main
+# ########
 
+# Always good
+check_env
+
+# Handle mouse clicks for the status bar (statuscmd patch for dwm)
+case "$BLOCK_BUTTON" in
+1) # Left click
+  notify_batteries "$(acpi -b)"
+  ;;
+2) # Middle click
+  notify_batteries "$(super tlp fullcharge)"
+  ;;
+3) # Right click
+  "$TERMINAL" -e "$EDITOR" "$0"
+  ;;
+esac
+
+# Refresh block
+get_batteries
